const express = require('express');
const app = express();
const cors = require('cors')

app.use(express.json())
app.use(cors())


app.set('port', process.env.PORT || 3000);
app.locals.title = 'Stacks';



app.listen(app.get('port'), () => {
    console.log(`${app.locals.title} is running on http://localhost:${app.get('port')}.`);
})

app.locals.albums = [
    {
        id: 'P-AL-33453-4L',
        albumName: 'Wish You Were Here',
        artist: 'Pink Floyd',
        releaseDate: 'September 12th, 1975',
        genre: 'Progressive Rock',
        bandMembers: ['Roger Waters', 'David Gilmour', 'Rick Wright', 'Nick Mason'],
        label: 'Harvest/Columbia',
        isBandTogether: false,
        rollingStoneReview: '*****',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=TMy_mYkwl4M',
        imgURL: 'https://upload.wikimedia.org/wikipedia/en/a/a4/Pink_Floyd%2C_Wish_You_Were_Here_%281975%29.png',
        albumsSold: 130000000,
    },
    {
        id: 'S-66100-724352775316',
        albumName: 'Kid A',
        artist: 'Radiohead',
        releaseDate: 'October 2nd, 2000',
        genre: 'Alternative Rock',
        bandMembers: ['Thom Yorke', 'Jonny Greenwood', 'Ed O/Brien', 'Phil Selway', 'Colin Greenwood'],
        label: 'Parlophone/Capitol',
        isBandTogether: true,
        rollingStoneReview: '****',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=NUnXxh5U25Y&list=PLtP8IJbMRbLwJwxyaCUaUWtBo1KK2K7RG',
        imgURL: 'https://upload.wikimedia.org/wikipedia/en/0/02/Radioheadkida.png',
        albumsSold: 4000000,
    },
    {
        id: '61422-31160',
        albumName: 'Lateralus',
        artist: 'TOOL',
        releaseDate: 'May 15th, 2001',
        genre: 'Progressive Metal',
        bandMembers: ['Maynard James Keenan', 'Adam Jones', 'Danny Carey', 'Justin Chancellor'],
        label: 'Volcano',
        isBandTogether: true,
        rollingStoneReview: '****',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=3BXyEUOuNds&list=PLESF6Vbm19P2IGN0wvksh-SYVWWj4lrxN',
        imgURL: 'https://upload.wikimedia.org/wikipedia/en/6/63/Tool_-_Lateralus.jpg',
        albumsSold: 3470000,
    },
    {
        id: '82876-50133-BB-SB-REI',
        albumName: 'Speakerboxxx/The Love Below',
        artist: 'Outkast',
        releaseDate: 'September 23rd, 2003',
        genre: 'Hip-Hop',
        bandMembers: ['Antwan Andre Patton', 'Andre Lauren Benjamin'],
        label: 'Arista',
        isBandTogether: true,
        rollingStoneReview: '***',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=RWof0wCG0Mw&list=PLC80P4gsPr-btAs663t1glvlOmy7kCUTi',
        imgURL: 'https://upload.wikimedia.org/wikipedia/en/5/54/Speakerboxxx-The_Love_Below.png',
        albumsSold: 11000000,
    },
    {
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D`Angelo',
        releaseDate: 'January 25th, 2000',
        genre: 'Neo-soul',
        bandMembers: ['Michael Euguene Archer', 'Ahmir Thompson', 'Pino Palladino', 'Charlie Hunter'],
        label: 'Virgin',
        isBandTogether: false,
        rollingStoneReview: '***',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=eo3iqsOH_54&list=PLj0iicDFTqJq8CcEMDS1VUbT0DPjFYOm1',
        imgURL: 'https://upload.wikimedia.org/wikipedia/en/c/cc/Voodoo_UK.jpg',
        albumsSold: 1700000
    },
    {
        id: '602547306777',
        albumName: 'Currents',
        artist: 'Tame Impala',
        releaseDate: 'July 17th, 2015',
        genre: 'Psychedelic Pop',
        bandMembers: ['Kevin Parker'],
        label: 'Modular',
        isBandTogether: true,
        rollingStoneReview: '****',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=LM6b85stNWI',
        imgURL: 'https://upload.wikimedia.org/wikipedia/en/9/9b/Tame_Impala_-_Currents.png',
        albumsSold: 1325034,
    },
     {
        id: '07243-849608',
        albumName: 'Discovery',
        artist: 'Daft Punk',
        releaseDate: 'March 12th, 2001',
        genre: 'Electro-funk',
        bandMembers: ['Thomas Bangalter', 'Guy-Manuel de Homem-Christo'],
        label: 'Daft House',
        isBandTogether: true,
        rollingStoneReview: '***',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=A2VpR8HahKc&list=PLSdoVPM5WnndSQEXRz704yQkKwx76GvPV',
        imgURL: 'https://upload.wikimedia.org/wikipedia/en/2/27/Daft_Punk_-_Discovery.png',
        albumsSold: 2856000,
    }, 
    {
        id: 'DFA-2250LP',
        albumName: 'This is Happening',
        artist: 'LCD Soundsystem',
        releaseDate: 'May 17th, 2010',
        genre: 'Dance-Punk',
        bandMembers: ['James Murphy', 'Nancy Whang', 'Pat Mahoney', 'Tyler Pope', 'Al Doyle', 'Matt Thornley', 'Korey Richey'],
        label: 'DFA/Virgin/Parlophone',
        isBandTogether: true,
        rollingStoneReview: '****',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=9ZNkPA_zUd4&list=OLAK5uy_lGgRvgGZf4SkJH8vN5Vt-5JBPwxgqNGgQ',
        imgURL: 'https://upload.wikimedia.org/wikipedia/en/7/7e/Lcdthisishappening.jpg',
        albumsSold: 300000,
    }, 
    {
        id: 'V6-8409',
        albumName: 'The Essential Charlie Parker',
        artist: 'Charlie Parker',
        releaseDate: '1961',
        genre: 'Bop Jazz',
        bandMembers: ['Charlie Parker', 'Max Roach', 'Thelonius Monk', 'Miles Davis', 'Dizzy Gillespie', 'Teddy Kotick'],
        label: 'Verve',
        isBandTogether: false,
        rollingStoneReview: null,
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=yOKtvLqzhBg',
        imgURL: 'https://i.discogs.com/pzRJY2IbBKGnkaw9-jT1w7Y1ImsnTSg7-twB_ycnEzw/rs:fit/g:sm/q:90/h:591/w:592/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMzNDI2/NzQtMTM5Mjc1NjUx/OS00MjUwLmpwZWc.jpeg',
        albumsSold: null,
    }, 
    {
        id: 'AFL1-2686',
        albumName: 'Waylon & Willie',
        artist: 'Willie Nelson',
        releaseDate: 'January 1978',
        genre: 'Outlaw Country',
        bandMembers: ['Willie Nelson', 'Waylon Jennings'],
        label: 'RCA',
        isBandTogether: false,
        rollingStoneReview: null,
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=i85ob2DackI&list=OLAK5uy_nOKWcp0nCDApfOzl2YXxfc3OaJMdvBtIM',
        imgURL: 'https://upload.wikimedia.org/wikipedia/en/9/9a/JenningsNelsonWaylon%26Willie.jpg',
        albumsSold: 21000000,
    }, 
    {
        id: 'T-416',
        albumName: 'The Hit Makers!',
        artist: 'Les Paul and Mary Ford',
        releaseDate: 1955,
        genre: 'Jazz & Swing',
        bandMembers: ['Les Paul', 'Mary Ford'],
        label: 'Capitol',
        isBandTogether: false,
        rollingStoneReview: null,
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=6agWO5f4Tzs',
        imgURL: 'https://i.discogs.com/pK2s6x4w0YRfEUrzE5Gd-bdL5jAb7LjHv-V8Tnwqlek/rs:fit/g:sm/q:90/h:596/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIyMDYx/MTUtMTQ2NDQ0NjI3/MS01NDgxLmpwZWc.jpeg',
        albumsSold: null,
    }, 
    {
        id: 'CL-2249',
        albumName: 'WEDNESDAY MORNING, 3AM',
        artist: 'Simon and Garfunkel',
        releaseDate: 'October 19th, 1964',
        genre: 'Folk',
        bandMembers: ['Paul Simon', 'Art Garfunkel'],
        label: 'Columbia',
        isBandTogether: false,
        rollingStoneReview: null,
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=1CAlRaLHINw&list=PLiN-7mukU_RGs6EIvLhRff-PVLG25otOV',
        imgURL: 'https://upload.wikimedia.org/wikipedia/en/2/2c/Simon_%26_Garfunkel%2C_Wednesday_Morning%2C_3_A.M._%281964%29.png',
        albumsSold: 1000000,
    }, 
    {
        id: 'EKS-74071',
        albumName: 'Fun House',
        artist: 'the Stooges',
        releaseDate: 'May 11th, 1970',
        genre: 'Proto-Punk',
        bandMembers: ['Iggy Pop', 'Ron Asheton', 'Scott Asheton', 'Dave Alexander', 'Steve Mackay'],
        label: 'Elektra',
        isBandTogether: false,
        rollingStoneReview: '*****',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=1OedEgzDl_I',
        imgURL: 'https://upload.wikimedia.org/wikipedia/en/6/6d/StoogesFunHouse.jpg',
        albumsSold: 89000,
    }, 
    {
        id: 'B0026745-01',
        albumName: 'DAMN',
        artist: 'Kendrick Lamar',
        releaseDate: 'July 14th, 2017',
        genre: 'Hip-Hop',
        bandMembers: ['Kendrick Lamar'],
        label: 'Interscope/Aftermath',
        isBandTogether: true,
        rollingStoneReview: '*****',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=5OaGBXAzFY0',
        imgURL: 'https://upload.wikimedia.org/wikipedia/en/5/51/Kendrick_Lamar_-_Damn.png',
        albumsSold: 4255414,
    }, 
    
]

app.get('/', (request, response) => {
    response.json(app.locals.albums)
});

// app.post('/', (req, res) => {

// })