const express = require('express');
const app = express();
const cors = require('cors')

app.use(express.json())
app.use(cors())

app.set('port', process.env.PORT || 3000);
app.locals.title = 'Stacks';

app.get('/', (request, response) => {
    response.send('');
});

app.listen(app.get('port'), () => {
    console.log(`${app.locals.title} is running on http://localhost:${app.get('port')}.`);
})

app.locals.albums = [
    {
        id: 1,
        albumName: 'Wish You Were Here',
        artist: 'Pink Floyd',
        releaseDate: 'September 12th, 1975',
        genre: 'Progressive Rock',
        bandMembers: ['Roger Waters', 'David Gilmour', 'Rick Wright', 'Nick Mason'],
        label:'Harvest/Columbia', 
        isBandTogether: false,
        rollingStoneReview:'*****',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=TMy_mYkwl4M',
        albumsSold: 130000000,
    },
    {
        id: 2,
        albumName: 'Kid A',
        artist: 'Radiohead',
        releaseDate: 'October 2nd, 2000',
        genre: 'Alternative Rock',
        bandMembers: ['Thom Yorke', 'Jonny Greenwood', 'Ed O/Brien', 'Phil Selway', 'Colin Greenwood' ],
        label: 'Parlophone/Capitol',
        isBandTogether: true,
        rollingStoneReview:'****',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=NUnXxh5U25Y&list=PLtP8IJbMRbLwJwxyaCUaUWtBo1KK2K7RG',
        albumsSold: 4000000,
    },
    {
        id: 3,
        albumName: 'Lateralus',
        artist: 'TOOL',
        releaseDate: 'May 15th, 2001',
        genre: 'Progressive Metal',
        bandMembers: ['Maynard James Keenan', 'Adam Jones', 'Danny Carey', 'Justin Chancellor'],
        label:'Volcano', 
        isBandTogether: true,
        rollingStoneReview:'****',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=3BXyEUOuNds&list=PLESF6Vbm19P2IGN0wvksh-SYVWWj4lrxN',
        albumsSold: 3470000,
    },
    {
        id: 4,
        albumName: 'Aquemini',
        artist: 'OutKast',
        releaseDate: 'September 29th, 1998',
        genre: 'Hip-Hop',
        bandMembers: ['Antwan Andre Patton', 'Andre Lauren Benjamin'],
        label: 'LaFace/Arista',
        isBandTogether: true,
        rollingStoneReview:'****',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=M4fwLA1_ARM',
        albumsSold: 2050000,
    },
    {
        id: 5,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 6,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 7,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 8,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 9,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 10,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 11,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 12,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 13,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 14,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 15,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 16,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 17,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 18,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 19,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 20,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 21,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 22,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 23,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 24,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 25,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 26,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 27,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 28,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 29,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },
    {
        id: 30,
        albumName: '',
        artist: '',
        releaseYear: 1980,
        genre: '',
        bandMembers: [],
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        albumsSold: 1,
    },

]