const express = require('express');
const app = express();
const cors = require('cors')

app.use(express.json())
app.use(cors())

app.set('port', process.env.PORT || 3000);
app.locals.title = 'Stacks';

app.get('/', (request, response) => {
    response.send('');
});

app.listen(app.get('port'), () => {
    console.log(`${app.locals.title} is running on http://localhost:${app.get('port')}.`);
})

app.locals.albums = [
    {
        id: 'P-AL-33453-4L',
        albumName: 'Wish You Were Here',
        artist: 'Pink Floyd',
        releaseDate: 'September 12th, 1975',
        genre: 'Progressive Rock',
        bandMembers: ['Roger Waters', 'David Gilmour', 'Rick Wright', 'Nick Mason'],
        label:'Harvest/Columbia', 
        isBandTogether: false,
        rollingStoneReview:'*****',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=TMy_mYkwl4M',
        imgURL: 'https://en.wikipedia.org/wiki/Wish_You_Were_Here_%28Pink_Floyd_album%29#/media/File:Pink_Floyd,_Wish_You_Were_Here_(1975).png',
        albumsSold: 130000000,
    },
    {
        id: 'S-66100-724352775316',
        albumName: 'Kid A',
        artist: 'Radiohead',
        releaseDate: 'October 2nd, 2000',
        genre: 'Alternative Rock',
        bandMembers: ['Thom Yorke', 'Jonny Greenwood', 'Ed O/Brien', 'Phil Selway', 'Colin Greenwood' ],
        label: 'Parlophone/Capitol',
        isBandTogether: true,
        rollingStoneReview:'****',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=NUnXxh5U25Y&list=PLtP8IJbMRbLwJwxyaCUaUWtBo1KK2K7RG',
        imgURL: 'https://upload.wikimedia.org/wikipedia/en/0/02/Radioheadkida.png',
        albumsSold: 4000000,
    },
    {
        id: 3,
        albumName: 'Lateralus',
        artist: 'TOOL',
        releaseDate: 'May 15th, 2001',
        genre: 'Progressive Metal',
        bandMembers: ['Maynard James Keenan', 'Adam Jones', 'Danny Carey', 'Justin Chancellor'],
        label:'Volcano', 
        isBandTogether: true,
        rollingStoneReview:'****',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=3BXyEUOuNds&list=PLESF6Vbm19P2IGN0wvksh-SYVWWj4lrxN',
        albumsSold: 3470000,
    },
    {
        id: '82876-50133-BB-SB-REI',
        albumName: 'Speakerboxxx/The Love Below',
        artist: 'Outkast',
        releaseDate: 'September 23rd, 2003',
        genre: 'Hip-Hop',
        bandMembers: ['Antwan Andre Patton', 'Andre Lauren Benjamin'],
        label: 'Arista',
        isBandTogether: true,
        rollingStoneReview:'***',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=RWof0wCG0Mw&list=PLC80P4gsPr-btAs663t1glvlOmy7kCUTi',
        imgURL: 'https://en.wikipedia.org/wiki/Speakerboxxx/The_Love_Below#/media/File:Speakerboxxx-The_Love_Below.png',
        albumsSold: 11000000,
    },
    {
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D`Angelo',
        releaseDate: 'January 25th, 2000',
        genre: 'Neo-soul',
        bandMembers: ['Michael Euguene Archer','Ahmir Thompson', 'Pino Palladino', 'Charlie Hunter'],
        label:'Virgin',
        isBandTogether: false,
        rollingStoneReview:'***',
        youTubeAlbumURL: 'https://www.youtube.com/watch?v=eo3iqsOH_54&list=PLj0iicDFTqJq8CcEMDS1VUbT0DPjFYOm1',
        imgURL:'https://en.wikipedia.org/wiki/Voodoo_(D%27Angelo_album)#/media/File:Voodoo_UK.jpg',
        albumsSold: 1700000
    },
    {
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },{
        id: 'MCR-902',
        albumName: 'Voodoo',
        artist: 'D Angelo',
        releaseDate: 1980,
        genre: '',
        bandMembers: [],
        label:'',
        isBandTogether: true,
        rollingStoneReview:'',
        youTubeAlbumURL: '',
        imgURL:'',
        albumsSold: 1,
    },

]